workflows:
  ios-habit-tracker:
    name: Brethra iOS # Замініть на вашу назву, це для умовного обозначення білду.
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: RemoteXAPI
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: SCHEDULED
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.brethra.Brethra # Замініть на ваш фактичний bundle identifier
      vars:
        BUNDLE_ID: "com.brethra.Brethra" # Замініть на ваш фактичний bundle identifier
        XCODE_PROJECT: "Brethra.xcodeproj" # Замініть на ваш фактичну назву Xcode проекту
        XCODE_SCHEME: "Brethra" # Замініть на ваш фактичну назву Xcode схеми
      xcode: 26 # Тут треба актуальна версія xcode на момент збірки
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd "$CM_BUILD_DIR"
          if [ -n "$APP_STORE_APPLE_ID" ]; then
            LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
            agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          else
            echo "Skipping build number increment because APP_STORE_APPLE_ID is not set."
          fi
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
